void titulo ();
int menu_principal (int op);
int menu_medicos (int opm);
void cargar_medicos (tLista2 &lista2);
void agregar_medicos (tDoctor doctor, tLista2 &lista2);
void modificar_medicos(tLista2 &lista2);
void eliminar_medicos (tLista2 &lista2);
void ordenar_medicos (tLista2 &lista2);
void mostrar_medicos (tLista2 &lista2);
void archivar_medicos (tLista2 &lista2);